# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13BCcnykMdWsquIraprAZfFUOabcGSK-s
"""

import pandas as pd

data = pd.read_csv('sample_data/california_housing_train.csv')

filtered_data = data[(data['population'] >= 0) & (data['population'] <= 500)]

average_cost = filtered_data['median_house_value'].mean()

print("The average cost of a house, where the number of people is from 0 to 500, is:", average_cost)