# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sZp0geiLmUh2u8sKSEZ2i7KfbyKudaJN
"""

import pandas as pd

data = pd.read_csv('sample_data/california_housing_train.csv')

min_population = data['population'].min()

min_population_zone = data[data['population'] == min_population]

max_households = min_population_zone['households'].max()

print("The maximum households in the zone of the minimum population value is:", max_households)